// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppTrust.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// trust_solve_r
List trust_solve_r(Function objfun1, Function tryEval, NumericVector parinit, double rinit, double rmax, Nullable<NumericVector> parscale, int iterlim, double fterm, double mterm, bool minimize, bool blather);
RcppExport SEXP _RcppTrust_trust_solve_r(SEXP objfun1SEXP, SEXP tryEvalSEXP, SEXP parinitSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP parscaleSEXP, SEXP iterlimSEXP, SEXP ftermSEXP, SEXP mtermSEXP, SEXP minimizeSEXP, SEXP blatherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type objfun1(objfun1SEXP);
    Rcpp::traits::input_parameter< Function >::type tryEval(tryEvalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< double >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type parscale(parscaleSEXP);
    Rcpp::traits::input_parameter< int >::type iterlim(iterlimSEXP);
    Rcpp::traits::input_parameter< double >::type fterm(ftermSEXP);
    Rcpp::traits::input_parameter< double >::type mterm(mtermSEXP);
    Rcpp::traits::input_parameter< bool >::type minimize(minimizeSEXP);
    Rcpp::traits::input_parameter< bool >::type blather(blatherSEXP);
    rcpp_result_gen = Rcpp::wrap(trust_solve_r(objfun1, tryEval, parinit, rinit, rmax, parscale, iterlim, fterm, mterm, minimize, blather));
    return rcpp_result_gen;
END_RCPP
}
// trust_check_numeric_output_test
List trust_check_numeric_output_test(double value, Nullable<NumericVector> gradient, Nullable<NumericVector> hessian, int dimen, bool minimize);
RcppExport SEXP _RcppTrust_trust_check_numeric_output_test(SEXP valueSEXP, SEXP gradientSEXP, SEXP hessianSEXP, SEXP dimenSEXP, SEXP minimizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type gradient(gradientSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type hessian(hessianSEXP);
    Rcpp::traits::input_parameter< int >::type dimen(dimenSEXP);
    Rcpp::traits::input_parameter< bool >::type minimize(minimizeSEXP);
    rcpp_result_gen = Rcpp::wrap(trust_check_numeric_output_test(value, gradient, hessian, dimen, minimize));
    return rcpp_result_gen;
END_RCPP
}
// trust_solve_lagrange_multiplier_test
double trust_solve_lagrange_multiplier_test(NumericVector beta, NumericVector gq, double r, double C1, double C2, double C3);
RcppExport SEXP _RcppTrust_trust_solve_lagrange_multiplier_test(SEXP betaSEXP, SEXP gqSEXP, SEXP rSEXP, SEXP C1SEXP, SEXP C2SEXP, SEXP C3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gq(gqSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type C1(C1SEXP);
    Rcpp::traits::input_parameter< double >::type C2(C2SEXP);
    Rcpp::traits::input_parameter< double >::type C3(C3SEXP);
    rcpp_result_gen = Rcpp::wrap(trust_solve_lagrange_multiplier_test(beta, gq, r, C1, C2, C3));
    return rcpp_result_gen;
END_RCPP
}
// trust_solve_subproblem_test
List trust_solve_subproblem_test(NumericVector eigval, NumericMatrix eigvec, NumericVector gq, double r);
RcppExport SEXP _RcppTrust_trust_solve_subproblem_test(SEXP eigvalSEXP, SEXP eigvecSEXP, SEXP gqSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eigval(eigvalSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eigvec(eigvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gq(gqSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(trust_solve_subproblem_test(eigval, eigvec, gq, r));
    return rcpp_result_gen;
END_RCPP
}
// trust_ptr
SEXP trust_ptr();
RcppExport SEXP _RcppTrust_trust_ptr() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(trust_ptr());
    return rcpp_result_gen;
END_RCPP
}
// trust_solve_c_rosenbrock_test
List trust_solve_c_rosenbrock_test(NumericVector parinit, double rinit, double rmax, int iterlim, double fterm, double mterm, bool minimize, bool blather);
RcppExport SEXP _RcppTrust_trust_solve_c_rosenbrock_test(SEXP parinitSEXP, SEXP rinitSEXP, SEXP rmaxSEXP, SEXP iterlimSEXP, SEXP ftermSEXP, SEXP mtermSEXP, SEXP minimizeSEXP, SEXP blatherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type parinit(parinitSEXP);
    Rcpp::traits::input_parameter< double >::type rinit(rinitSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< int >::type iterlim(iterlimSEXP);
    Rcpp::traits::input_parameter< double >::type fterm(ftermSEXP);
    Rcpp::traits::input_parameter< double >::type mterm(mtermSEXP);
    Rcpp::traits::input_parameter< bool >::type minimize(minimizeSEXP);
    Rcpp::traits::input_parameter< bool >::type blather(blatherSEXP);
    rcpp_result_gen = Rcpp::wrap(trust_solve_c_rosenbrock_test(parinit, rinit, rmax, iterlim, fterm, mterm, minimize, blather));
    return rcpp_result_gen;
END_RCPP
}
// trust_openmp_stress_test
List trust_openmp_stress_test(int nStarts, int nThreadsRequested);
RcppExport SEXP _RcppTrust_trust_openmp_stress_test(SEXP nStartsSEXP, SEXP nThreadsRequestedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nStarts(nStartsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreadsRequested(nThreadsRequestedSEXP);
    rcpp_result_gen = Rcpp::wrap(trust_openmp_stress_test(nStarts, nThreadsRequested));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppTrust_trust_solve_r", (DL_FUNC) &_RcppTrust_trust_solve_r, 11},
    {"_RcppTrust_trust_check_numeric_output_test", (DL_FUNC) &_RcppTrust_trust_check_numeric_output_test, 5},
    {"_RcppTrust_trust_solve_lagrange_multiplier_test", (DL_FUNC) &_RcppTrust_trust_solve_lagrange_multiplier_test, 6},
    {"_RcppTrust_trust_solve_subproblem_test", (DL_FUNC) &_RcppTrust_trust_solve_subproblem_test, 4},
    {"_RcppTrust_trust_ptr", (DL_FUNC) &_RcppTrust_trust_ptr, 0},
    {"_RcppTrust_trust_solve_c_rosenbrock_test", (DL_FUNC) &_RcppTrust_trust_solve_c_rosenbrock_test, 8},
    {"_RcppTrust_trust_openmp_stress_test", (DL_FUNC) &_RcppTrust_trust_openmp_stress_test, 2},
    {NULL, NULL, 0}
};

void trust_register_ccallable(DllInfo *dll);
RcppExport void R_init_RcppTrust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    trust_register_ccallable(dll);
}
