# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

minqa_bobyqa_r <- function(par, lower, upper, ctrl, fn) {
    .Call(`_RcppTrust_minqa_bobyqa_r`, par, lower, upper, ctrl, fn)
}

minqa_newuoa_r <- function(par, ctrl, fn) {
    .Call(`_RcppTrust_minqa_newuoa_r`, par, ctrl, fn)
}

solver_openmp_stress_test <- function(solver, n, nStarts, nThreadsRequested) {
    .Call(`_RcppTrust_solver_openmp_stress_test`, solver, n, nStarts, nThreadsRequested)
}

solver_c_api_edge_test <- function() {
    .Call(`_RcppTrust_solver_c_api_edge_test`)
}

steihaug_solve_r <- function(par, fn, gr, hess, hessvec, control) {
    .Call(`_RcppTrust_steihaug_solve_r`, par, fn, gr, hess, hessvec, control)
}

trust_solve_r <- function(objfun1, tryEval, parinit, rinit, rmax, parscale, iterlim, fterm, mterm, minimize, blather) {
    .Call(`_RcppTrust_trust_solve_r`, objfun1, tryEval, parinit, rinit, rmax, parscale, iterlim, fterm, mterm, minimize, blather)
}

trust_check_numeric_output_test <- function(value, gradient, hessian, dimen, minimize) {
    .Call(`_RcppTrust_trust_check_numeric_output_test`, value, gradient, hessian, dimen, minimize)
}

trust_solve_lagrange_multiplier_test <- function(beta, gq, r, C1, C2, C3) {
    .Call(`_RcppTrust_trust_solve_lagrange_multiplier_test`, beta, gq, r, C1, C2, C3)
}

trust_solve_subproblem_test <- function(eigval, eigvec, gq, r) {
    .Call(`_RcppTrust_trust_solve_subproblem_test`, eigval, eigvec, gq, r)
}

trust_ptr <- function() {
    .Call(`_RcppTrust_trust_ptr`)
}

trust_solve_c_rosenbrock_test <- function(parinit, rinit, rmax, iterlim, fterm, mterm, minimize, blather) {
    .Call(`_RcppTrust_trust_solve_c_rosenbrock_test`, parinit, rinit, rmax, iterlim, fterm, mterm, minimize, blather)
}

trust_openmp_stress_test <- function(nStarts, nThreadsRequested) {
    .Call(`_RcppTrust_trust_openmp_stress_test`, nStarts, nThreadsRequested)
}

