# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trust_solve_r <- function(objfun1, tryEval, parinit, rinit, rmax, parscale, iterlim, fterm, mterm, minimize, blather) {
    .Call(`_RcppTrust_trust_solve_r`, objfun1, tryEval, parinit, rinit, rmax, parscale, iterlim, fterm, mterm, minimize, blather)
}

trust_check_numeric_output_test <- function(value, gradient, hessian, dimen, minimize) {
    .Call(`_RcppTrust_trust_check_numeric_output_test`, value, gradient, hessian, dimen, minimize)
}

trust_solve_lagrange_multiplier_test <- function(beta, gq, r, C1, C2, C3) {
    .Call(`_RcppTrust_trust_solve_lagrange_multiplier_test`, beta, gq, r, C1, C2, C3)
}

trust_solve_subproblem_test <- function(eigval, eigvec, gq, r) {
    .Call(`_RcppTrust_trust_solve_subproblem_test`, eigval, eigvec, gq, r)
}

trust_ptr <- function() {
    .Call(`_RcppTrust_trust_ptr`)
}

trust_solve_c_rosenbrock_test <- function(parinit, rinit, rmax, iterlim, fterm, mterm, minimize, blather) {
    .Call(`_RcppTrust_trust_solve_c_rosenbrock_test`, parinit, rinit, rmax, iterlim, fterm, mterm, minimize, blather)
}

trust_openmp_stress_test <- function(nStarts, nThreadsRequested) {
    .Call(`_RcppTrust_trust_openmp_stress_test`, nStarts, nThreadsRequested)
}

